//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev.Editor.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dev.Editor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu // The following example binary definition processes a bitmap file (.BMP)
        ///// and provides information decoded from the bitmap header.
        ///
        ///struct BmpHeader 
        ///{
        ///    char[2] descriptor;
        ///    int bmpSizeInBytes;
        ///    short reserved1;
        ///    short reserved2;
        ///    int dataOffset;
        ///};
        ///
        ///enum DibHeaderType : byte 
        ///{
        /// BITMAPCOREHEADER = 1u,
        /// OS21XBITMAPHEADER = 2u,
        /// OS22XBITMAPHEADER_V1 = 3u,
        /// OS22XBITMAPHEADER_V2 = 4u,
        /// BITMAPINFOHEADER = 5u,
        /// BITMAPV2INFOHEADER = 6u,
        /// BITMAPV3INFOHEADER = 7u,
        /// BITMAPV4HEA [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string BinDefinitionSample {
            get {
                return ResourceManager.GetString("BinDefinitionSample", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Document.
        /// </summary>
        public static string BlankDocName {
            get {
                return ResourceManager.GetString("BlankDocName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Document.
        /// </summary>
        public static string BlankDocumentName {
            get {
                return ResourceManager.GetString("BlankDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Messages.
        /// </summary>
        public static string BottomTool_Messages_Title {
            get {
                return ResourceManager.GetString("BottomTool.Messages.Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search results.
        /// </summary>
        public static string BottomTool_SearchResults_Title {
            get {
                return ResourceManager.GetString("BottomTool.SearchResults.Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Syntax highlighting {0}.
        /// </summary>
        public static string Command_SetHighlighting {
            get {
                return ResourceManager.GetString("Command.SetHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Toggle line numbers.
        /// </summary>
        public static string Command_ToggleLineNumbers {
            get {
                return ResourceManager.GetString("Command.ToggleLineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Toggle word wrap.
        /// </summary>
        public static string Command_ToggleWordWrap {
            get {
                return ResourceManager.GetString("Command.ToggleWordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Behavior.
        /// </summary>
        public static string Configuration_Behavior {
            get {
                return ResourceManager.GetString("Configuration.Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Closing behavior.
        /// </summary>
        public static string Configuration_Behavior_ClosingBehavior {
            get {
                return ResourceManager.GetString("Configuration.Behavior.ClosingBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose, how application should behave when closing:.
        /// </summary>
        public static string Configuration_Behavior_ClosingBehavior_Comment {
            get {
                return ResourceManager.GetString("Configuration.Behavior.ClosingBehavior.Comment", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fluent.
        /// </summary>
        public static string Configuration_Behavior_ClosingBehavior_Fluent {
            get {
                return ResourceManager.GetString("Configuration.Behavior.ClosingBehavior.Fluent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dev.Editor will store all open documents and restore them on startup (including unsaved changes).
        /// </summary>
        public static string Configuration_Behavior_ClosingBehavior_Fluent_Comment {
            get {
                return ResourceManager.GetString("Configuration.Behavior.ClosingBehavior.Fluent.Comment", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Standard.
        /// </summary>
        public static string Configuration_Behavior_ClosingBehavior_Standard {
            get {
                return ResourceManager.GetString("Configuration.Behavior.ClosingBehavior.Standard", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dev.Editor will close all documents upon closing and start with blank new document.
        /// </summary>
        public static string Configuration_Behavior_ClosingBehavior_Standard_Comment {
            get {
                return ResourceManager.GetString("Configuration.Behavior.ClosingBehavior.Standard.Comment", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu System.
        /// </summary>
        public static string Configuration_System {
            get {
                return ResourceManager.GetString("Configuration.System", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Disable integration.
        /// </summary>
        public static string Configuration_System_Integration_Disable {
            get {
                return ResourceManager.GetString("Configuration.System.Integration.Disable", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Integration is disabled.
        /// </summary>
        public static string Configuration_System_Integration_Disabled {
            get {
                return ResourceManager.GetString("Configuration.System.Integration.Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enable integration.
        /// </summary>
        public static string Configuration_System_Integration_Enable {
            get {
                return ResourceManager.GetString("Configuration.System.Integration.Enable", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Integration is enabled.
        /// </summary>
        public static string Configuration_System_Integration_Enabled {
            get {
                return ResourceManager.GetString("Configuration.System.Integration.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu System context menu integration.
        /// </summary>
        public static string Configuration_System_IntegrationHeader {
            get {
                return ResourceManager.GetString("Configuration.System.IntegrationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Integration state.
        /// </summary>
        public static string Configuration_System_IntegrationState {
            get {
                return ResourceManager.GetString("Configuration.System.IntegrationState", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Configuration.
        /// </summary>
        public static string Configuration_Title {
            get {
                return ResourceManager.GetString("Configuration.Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu First document.
        /// </summary>
        public static string ConfigureDiffDialog_FirstDocument {
            get {
                return ResourceManager.GetString("ConfigureDiffDialog.FirstDocument", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ignore case.
        /// </summary>
        public static string ConfigureDiffDialog_IgnoreCase {
            get {
                return ResourceManager.GetString("ConfigureDiffDialog.IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ignore whitespace.
        /// </summary>
        public static string ConfigureDiffDialog_IgnoreWhitespace {
            get {
                return ResourceManager.GetString("ConfigureDiffDialog.IgnoreWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Options.
        /// </summary>
        public static string ConfigureDiffDialog_Options {
            get {
                return ResourceManager.GetString("ConfigureDiffDialog.Options", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Second document.
        /// </summary>
        public static string ConfigureDiffDialog_SecondDocument {
            get {
                return ResourceManager.GetString("ConfigureDiffDialog.SecondDocument", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Source.
        /// </summary>
        public static string ConfigureDiffDialog_Source {
            get {
                return ResourceManager.GetString("ConfigureDiffDialog.Source", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Compare documents.
        /// </summary>
        public static string ConfigureDiffDialog_Title {
            get {
                return ResourceManager.GetString("ConfigureDiffDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unescape.
        /// </summary>
        public static string ConfigureEscapeDialog_BackwardTitle {
            get {
                return ResourceManager.GetString("ConfigureEscapeDialog.BackwardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Configuration.
        /// </summary>
        public static string ConfigureEscapeDialog_Configure {
            get {
                return ResourceManager.GetString("ConfigureEscapeDialog.Configure", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Escape character.
        /// </summary>
        public static string ConfigureEscapeDialog_EscapeCharacter {
            get {
                return ResourceManager.GetString("ConfigureEscapeDialog.EscapeCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Escape double quotes.
        /// </summary>
        public static string ConfigureEscapeDialog_EscapeDoubleQuotes {
            get {
                return ResourceManager.GetString("ConfigureEscapeDialog.EscapeDoubleQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Double quotes.
        /// </summary>
        public static string ConfigureEscapeDialog_EscapeDoubleQuotes_Label {
            get {
                return ResourceManager.GetString("ConfigureEscapeDialog.EscapeDoubleQuotes.Label", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Escape single quotes.
        /// </summary>
        public static string ConfigureEscapeDialog_EscapeSingleQuotes {
            get {
                return ResourceManager.GetString("ConfigureEscapeDialog.EscapeSingleQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Single quotes.
        /// </summary>
        public static string ConfigureEscapeDialog_EscapeSingleQuotes_Label {
            get {
                return ResourceManager.GetString("ConfigureEscapeDialog.EscapeSingleQuotes.Label", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Include line breaks (\n), tabs (\t) etc..
        /// </summary>
        public static string ConfigureEscapeDialog_EscapeSpecialCharacters {
            get {
                return ResourceManager.GetString("ConfigureEscapeDialog.EscapeSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Special characters.
        /// </summary>
        public static string ConfigureEscapeDialog_EscapeSpecialCharacters_Label {
            get {
                return ResourceManager.GetString("ConfigureEscapeDialog.EscapeSpecialCharacters.Label", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Escape.
        /// </summary>
        public static string ConfigureEscapeDialog_ForwardTitle {
            get {
                return ResourceManager.GetString("ConfigureEscapeDialog.ForwardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Escape.
        /// </summary>
        public static string ConfigureEscapeDialog_Title_Escape {
            get {
                return ResourceManager.GetString("ConfigureEscapeDialog.Title.Escape", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unescape.
        /// </summary>
        public static string ConfigureEscapeDialog_Title_Unescape {
            get {
                return ResourceManager.GetString("ConfigureEscapeDialog.Title.Unescape", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dev.Editor.
        /// </summary>
        public static string DefaultDialogTitle {
            get {
                return ResourceManager.GetString("DefaultDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu All files (*.*)|*.*.
        /// </summary>
        public static string DefaultFilter {
            get {
                return ResourceManager.GetString("DefaultFilter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dev.Editor.
        /// </summary>
        public static string DefaultMessageboxTitle {
            get {
                return ResourceManager.GetString("DefaultMessageboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Binary definition.
        /// </summary>
        public static string Dialog_BinDefinition_Title {
            get {
                return ResourceManager.GetString("Dialog.BinDefinition.Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        public static string Dialog_Name_Name {
            get {
                return ResourceManager.GetString("Dialog.Name.Name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Stored search.
        /// </summary>
        public static string Dialog_StoredSearch_Title {
            get {
                return ResourceManager.GetString("Dialog.StoredSearch.Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Close.
        /// </summary>
        public static string DocumentHeader_ContextMenu_Close {
            get {
                return ResourceManager.GetString("DocumentHeader.ContextMenu.Close", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Close all.
        /// </summary>
        public static string DocumentHeader_ContextMenu_CloseAll {
            get {
                return ResourceManager.GetString("DocumentHeader.ContextMenu.CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Close all but pinned.
        /// </summary>
        public static string DocumentHeader_ContextMenu_CloseAllButPinned {
            get {
                return ResourceManager.GetString("DocumentHeader.ContextMenu.CloseAllButPinned", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Close others.
        /// </summary>
        public static string DocumentHeader_ContextMenu_CloseOthers {
            get {
                return ResourceManager.GetString("DocumentHeader.ContextMenu.CloseOthers", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Move to other view.
        /// </summary>
        public static string DocumentHeader_ContextMenu_MoveToOtherView {
            get {
                return ResourceManager.GetString("DocumentHeader.ContextMenu.MoveToOtherView", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tab color.
        /// </summary>
        public static string DocumentHeader_ContextMenu_TabColor {
            get {
                return ResourceManager.GetString("DocumentHeader.ContextMenu.TabColor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Blue.
        /// </summary>
        public static string DocumentHeader_ContextMenu_TabColor_Blue {
            get {
                return ResourceManager.GetString("DocumentHeader.ContextMenu.TabColor.Blue", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Default.
        /// </summary>
        public static string DocumentHeader_ContextMenu_TabColor_Default {
            get {
                return ResourceManager.GetString("DocumentHeader.ContextMenu.TabColor.Default", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Green.
        /// </summary>
        public static string DocumentHeader_ContextMenu_TabColor_Green {
            get {
                return ResourceManager.GetString("DocumentHeader.ContextMenu.TabColor.Green", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Red.
        /// </summary>
        public static string DocumentHeader_ContextMenu_TabColor_Red {
            get {
                return ResourceManager.GetString("DocumentHeader.ContextMenu.TabColor.Red", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Yellow.
        /// </summary>
        public static string DocumentHeader_ContextMenu_TabColor_Yellow {
            get {
                return ResourceManager.GetString("DocumentHeader.ContextMenu.TabColor.Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ....
        /// </summary>
        public static string Ellipsis {
            get {
                return ResourceManager.GetString("Ellipsis", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unhandled exception occurred in the application. You may find details below..
        /// </summary>
        public static string ExceptionWindow_ExceptionDetails {
            get {
                return ResourceManager.GetString("ExceptionWindow.ExceptionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Exception details.
        /// </summary>
        public static string ExceptionWindow_Header {
            get {
                return ResourceManager.GetString("ExceptionWindow.Header", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unhandled exception.
        /// </summary>
        public static string ExceptionWindow_Title {
            get {
                return ResourceManager.GetString("ExceptionWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu XSLT sheets (*.xsl)|*.xsl.
        /// </summary>
        public static string Filter_Xslt {
            get {
                return ResourceManager.GetString("Filter.Xslt", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot perform assignment to {0}. Reason:
        ///{1}.
        /// </summary>
        public static string Message_AnalysisError_CannotAssign {
            get {
                return ResourceManager.GetString("Message.AnalysisError.CannotAssign", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot add evaluated field {0}. Reason:
        ///{1}.
        /// </summary>
        public static string Message_AnalysisError_CannotShow {
            get {
                return ResourceManager.GetString("Message.AnalysisError.CannotShow", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to read field {0}. Reason:
        ///{1}.
        /// </summary>
        public static string Message_AnalysisError_FailedToReadField {
            get {
                return ResourceManager.GetString("Message.AnalysisError.FailedToReadField", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to read struct field {0}. Reason:
        ///{1}.
        /// </summary>
        public static string Message_AnalysisError_FailedToReadStruct {
            get {
                return ResourceManager.GetString("Message.AnalysisError.FailedToReadStruct", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to read struct array field {0}. Reason:
        ///{1}.
        /// </summary>
        public static string Message_AnalysisError_FailedToReadStructArray {
            get {
                return ResourceManager.GetString("Message.AnalysisError.FailedToReadStructArray", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to skip bytes. Reason:
        ///{0}.
        /// </summary>
        public static string Message_AnalysisError_FailedToSkip {
            get {
                return ResourceManager.GetString("Message.AnalysisError.FailedToSkip", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Condition in if statement must evaluate to bool value!.
        /// </summary>
        public static string Message_AnalysisError_InvalidIfCondition {
            get {
                return ResourceManager.GetString("Message.AnalysisError.InvalidIfCondition", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unexpected end of file!.
        /// </summary>
        public static string Message_AnalysisError_UnexpectedEndOfStream {
            get {
                return ResourceManager.GetString("Message.AnalysisError.UnexpectedEndOfStream", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure you want to delete binary definition {0}?.
        /// </summary>
        public static string Message_BinDefinitionDeleteConfirmation {
            get {
                return ResourceManager.GetString("Message.BinDefinitionDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot add binary definition, error: {0}.
        /// </summary>
        public static string Message_CannotAddBinDefinition {
            get {
                return ResourceManager.GetString("Message.CannotAddBinDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot format - XML is invalid..
        /// </summary>
        public static string Message_CannotFormatInvalidXml {
            get {
                return ResourceManager.GetString("Message.CannotFormatInvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot open binary file. See Messages window for details..
        /// </summary>
        public static string Message_CannotOpenBinFile {
            get {
                return ResourceManager.GetString("Message.CannotOpenBinFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot open file {0}. Error: {1}.
        /// </summary>
        public static string Message_CannotOpenFile {
            get {
                return ResourceManager.GetString("Message.CannotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot restore file {0}. Error message: {1}.
        /// </summary>
        public static string Message_CannotRestoreFile {
            get {
                return ResourceManager.GetString("Message.CannotRestoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot save configuration file. Are you sure you want to exit?.
        /// </summary>
        public static string Message_CannotSaveConfiguration {
            get {
                return ResourceManager.GetString("Message.CannotSaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot save file {0}. Error: {1}.
        /// </summary>
        public static string Message_CannotSaveFile {
            get {
                return ResourceManager.GetString("Message.CannotSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot transform XML file with XSLT. See Messages window for details..
        /// </summary>
        public static string Message_CannotTransformXslt {
            get {
                return ResourceManager.GetString("Message.CannotTransformXslt", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu File {0} was deleted. Do you want to keep it in the editor?.
        /// </summary>
        public static string Message_DocumentDeleted {
            get {
                return ResourceManager.GetString("Message.DocumentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu File {0} was modified outside the editor. Do you want to reload it?.
        /// </summary>
        public static string Message_DocumentModifiedOutsideEditor {
            get {
                return ResourceManager.GetString("Message.DocumentModifiedOutsideEditor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Documents have no differences..
        /// </summary>
        public static string Message_DocumentsAreSame {
            get {
                return ResourceManager.GetString("Message.DocumentsAreSame", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot access member {0} of field {1}..
        /// </summary>
        public static string Message_EvalError_CannotAccessMember {
            get {
                return ResourceManager.GetString("Message.EvalError.CannotAccessMember", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot find identifier {0} in current scope..
        /// </summary>
        public static string Message_EvalError_CannotFindIdentifier {
            get {
                return ResourceManager.GetString("Message.EvalError.CannotFindIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enum {0} does not contain member {1}..
        /// </summary>
        public static string Message_EvalError_EnumDoesNotContainMember {
            get {
                return ResourceManager.GetString("Message.EvalError.EnumDoesNotContainMember", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to evaluate binary operator. Reason:
        ///{0}.
        /// </summary>
        public static string Message_EvalError_FailedToEvalBinaryOperator {
            get {
                return ResourceManager.GetString("Message.EvalError.FailedToEvalBinaryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to evaluate expression. Reason:
        ///{0}.
        /// </summary>
        public static string Message_EvalError_FailedToEvalExpression {
            get {
                return ResourceManager.GetString("Message.EvalError.FailedToEvalExpression", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Identifier {0} does not point to a value-type field..
        /// </summary>
        public static string Message_EvalError_MemberIsNotValue {
            get {
                return ResourceManager.GetString("Message.EvalError.MemberIsNotValue", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to escape string!.
        /// </summary>
        public static string Message_FailedToEscapeString {
            get {
                return ResourceManager.GetString("Message.FailedToEscapeString", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to unescape string!.
        /// </summary>
        public static string Message_FailedToUnescapeString {
            get {
                return ResourceManager.GetString("Message.FailedToUnescapeString", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Do you want to save document {0} before closing?.
        /// </summary>
        public static string Message_FileNotSaved {
            get {
                return ResourceManager.GetString("Message.FileNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Found occurrences: {0}..
        /// </summary>
        public static string Message_FoundOccurrences {
            get {
                return ResourceManager.GetString("Message.FoundOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid Base64 string!.
        /// </summary>
        public static string Message_InvalidBase64String {
            get {
                return ResourceManager.GetString("Message.InvalidBase64String", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid search pattern!.
        /// </summary>
        public static string Message_InvalidSearchPattern {
            get {
                return ResourceManager.GetString("Message.InvalidSearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid folder for search!.
        /// </summary>
        public static string Message_LocationInvalid {
            get {
                return ResourceManager.GetString("Message.LocationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot find any occurrences of entered text..
        /// </summary>
        public static string Message_NoMorePatternsFound {
            get {
                return ResourceManager.GetString("Message.NoMorePatternsFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Replaced occurrences: {0}..
        /// </summary>
        public static string Message_ReplacedOccurrences {
            get {
                return ResourceManager.GetString("Message.ReplacedOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search reached beginning of the file. Do you want to continue from the end?.
        /// </summary>
        public static string Message_SearchReachedBeginning {
            get {
                return ResourceManager.GetString("Message.SearchReachedBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search reached end of the file. Do you want to continue from the beginning?.
        /// </summary>
        public static string Message_SearchReachedEnd {
            get {
                return ResourceManager.GetString("Message.SearchReachedEnd", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure you want to delete stored search &quot;{0}&quot;?.
        /// </summary>
        public static string Message_StoredSearchDeleteConfirmation {
            get {
                return ResourceManager.GetString("Message.StoredSearchDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cannot find type name {0} !.
        /// </summary>
        public static string Message_SyntaxError_CannotFindTypeName {
            get {
                return ResourceManager.GetString("Message.SyntaxError.CannotFindTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enum item with value {0} already exists!.
        /// </summary>
        public static string Message_SyntaxError_EnumItemValueDuplicated {
            get {
                return ResourceManager.GetString("Message.SyntaxError.EnumItemValueDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to process definition!.
        /// </summary>
        public static string Message_SyntaxError_FailedToProcessDefinition {
            get {
                return ResourceManager.GetString("Message.SyntaxError.FailedToProcessDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Field with name {0} already exists!.
        /// </summary>
        public static string Message_SyntaxError_FieldAlreadyExists {
            get {
                return ResourceManager.GetString("Message.SyntaxError.FieldAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enum member {0} value ({1}) is outside underlying integer type range ({2})!.
        /// </summary>
        public static string Message_SyntaxError_IntegerValueOutsideRange {
            get {
                return ResourceManager.GetString("Message.SyntaxError.IntegerValueOutsideRange", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid floating point value: {0} !.
        /// </summary>
        public static string Message_SyntaxError_InvalidFloatNumber {
            get {
                return ResourceManager.GetString("Message.SyntaxError.InvalidFloatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid integer value: {0} !.
        /// </summary>
        public static string Message_SyntaxError_InvalidIntegerValue {
            get {
                return ResourceManager.GetString("Message.SyntaxError.InvalidIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Signed-type enum should contain only signed int values!.
        /// </summary>
        public static string Message_SyntaxError_InvalidSignedEnumItem {
            get {
                return ResourceManager.GetString("Message.SyntaxError.InvalidSignedEnumItem", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unsigned-type enum should contain only unsigned int values (with suffix &quot;u&quot;)!.
        /// </summary>
        public static string Message_SyntaxError_InvalidUnsignedEnumItem {
            get {
                return ResourceManager.GetString("Message.SyntaxError.InvalidUnsignedEnumItem", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invalid unsigned integer value: {0}!.
        /// </summary>
        public static string Message_SyntaxError_InvalidUnsignedIntegerValue {
            get {
                return ResourceManager.GetString("Message.SyntaxError.InvalidUnsignedIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Struct with name {0} already exists!.
        /// </summary>
        public static string Message_SyntaxError_StructureAlreadyExists {
            get {
                return ResourceManager.GetString("Message.SyntaxError.StructureAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Syntax error in definition: {0}.
        /// </summary>
        public static string Message_SyntaxError_SyntaxError {
            get {
                return ResourceManager.GetString("Message.SyntaxError.SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Double-click binary definition to open binary file and analyze it..
        /// </summary>
        public static string Message_UseSidePanelToOpenBinFile {
            get {
                return ResourceManager.GetString("Message.UseSidePanelToOpenBinFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Code.
        /// </summary>
        public static string Messages_Code {
            get {
                return ResourceManager.GetString("Messages.Code", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Column.
        /// </summary>
        public static string Messages_Column {
            get {
                return ResourceManager.GetString("Messages.Column", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu File.
        /// </summary>
        public static string Messages_File {
            get {
                return ResourceManager.GetString("Messages.File", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Message.
        /// </summary>
        public static string Messages_Message {
            get {
                return ResourceManager.GetString("Messages.Message", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Row.
        /// </summary>
        public static string Messages_Row {
            get {
                return ResourceManager.GetString("Messages.Row", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Severity.
        /// </summary>
        public static string Messages_Severity {
            get {
                return ResourceManager.GetString("Messages.Severity", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter name.
        /// </summary>
        public static string NameDialog_GroupBoxHeader {
            get {
                return ResourceManager.GetString("NameDialog.GroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Name.
        /// </summary>
        public static string NameDialog_Label {
            get {
                return ResourceManager.GetString("NameDialog.Label", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter name.
        /// </summary>
        public static string NameDialog_Title {
            get {
                return ResourceManager.GetString("NameDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Navigation.
        /// </summary>
        public static string NavigationPopup_Header {
            get {
                return ResourceManager.GetString("NavigationPopup.Header", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu // This is Dev.Editor&apos;s {0} binary file definition.
        ///.
        /// </summary>
        public static string NewBinaryDefinitionContents {
            get {
                return ResourceManager.GetString("NewBinaryDefinitionContents", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open binary file {0}.
        /// </summary>
        public static string OpenBinaryFile_Title {
            get {
                return ResourceManager.GetString("OpenBinaryFile.Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Markdown.
        /// </summary>
        public static string Ribbon_ContentGroup_Markdown {
            get {
                return ResourceManager.GetString("Ribbon.ContentGroup.Markdown", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu XML.
        /// </summary>
        public static string Ribbon_ContextGroup_Xml {
            get {
                return ResourceManager.GetString("Ribbon.ContextGroup.Xml", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Compare documents.
        /// </summary>
        public static string Ribbon_Home_Comparing_Compare {
            get {
                return ResourceManager.GetString("Ribbon.Home.Comparing.Compare", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Next change.
        /// </summary>
        public static string Ribbon_Home_Comparing_NextChange {
            get {
                return ResourceManager.GetString("Ribbon.Home.Comparing.NextChange", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Previous change.
        /// </summary>
        public static string Ribbon_Home_Comparing_PreviousChange {
            get {
                return ResourceManager.GetString("Ribbon.Home.Comparing.PreviousChange", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Copy.
        /// </summary>
        public static string Ribbon_Home_Edit_Copy {
            get {
                return ResourceManager.GetString("Ribbon.Home.Edit.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cut.
        /// </summary>
        public static string Ribbon_Home_Edit_Cut {
            get {
                return ResourceManager.GetString("Ribbon.Home.Edit.Cut", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Paste.
        /// </summary>
        public static string Ribbon_Home_Edit_Paste {
            get {
                return ResourceManager.GetString("Ribbon.Home.Edit.Paste", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Redo.
        /// </summary>
        public static string Ribbon_Home_Edit_Redo {
            get {
                return ResourceManager.GetString("Ribbon.Home.Edit.Redo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Undo.
        /// </summary>
        public static string Ribbon_Home_Edit_Undo {
            get {
                return ResourceManager.GetString("Ribbon.Home.Edit.Undo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New.
        /// </summary>
        public static string Ribbon_Home_File_New {
            get {
                return ResourceManager.GetString("Ribbon.Home.File.New", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New hex editor.
        /// </summary>
        public static string Ribbon_Home_File_NewHex {
            get {
                return ResourceManager.GetString("Ribbon.Home.File.NewHex", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open.
        /// </summary>
        public static string Ribbon_Home_File_Open {
            get {
                return ResourceManager.GetString("Ribbon.Home.File.Open", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open binary file.
        /// </summary>
        public static string Ribbon_Home_File_OpenBin {
            get {
                return ResourceManager.GetString("Ribbon.Home.File.OpenBin", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open in hex editor.
        /// </summary>
        public static string Ribbon_Home_File_OpenHex {
            get {
                return ResourceManager.GetString("Ribbon.Home.File.OpenHex", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save.
        /// </summary>
        public static string Ribbon_Home_File_Save {
            get {
                return ResourceManager.GetString("Ribbon.Home.File.Save", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save as.
        /// </summary>
        public static string Ribbon_Home_File_SaveAs {
            get {
                return ResourceManager.GetString("Ribbon.Home.File.SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Comparing.
        /// </summary>
        public static string Ribbon_Home_Group_Comparing {
            get {
                return ResourceManager.GetString("Ribbon.Home.Group.Comparing", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit.
        /// </summary>
        public static string Ribbon_Home_Group_Edit {
            get {
                return ResourceManager.GetString("Ribbon.Home.Group.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu File.
        /// </summary>
        public static string Ribbon_Home_Group_File {
            get {
                return ResourceManager.GetString("Ribbon.Home.Group.File", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Navigation.
        /// </summary>
        public static string Ribbon_Home_Group_Navigation {
            get {
                return ResourceManager.GetString("Ribbon.Home.Group.Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search.
        /// </summary>
        public static string Ribbon_Home_Group_Search {
            get {
                return ResourceManager.GetString("Ribbon.Home.Group.Search", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Navigation.
        /// </summary>
        public static string Ribbon_Home_Navigation_Navigate {
            get {
                return ResourceManager.GetString("Ribbon.Home.Navigation.Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Find next.
        /// </summary>
        public static string Ribbon_Home_Search_FindNext {
            get {
                return ResourceManager.GetString("Ribbon.Home.Search.FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Replace.
        /// </summary>
        public static string Ribbon_Home_Search_Replace {
            get {
                return ResourceManager.GetString("Ribbon.Home.Search.Replace", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search.
        /// </summary>
        public static string Ribbon_Home_Search_Search {
            get {
                return ResourceManager.GetString("Ribbon.Home.Search.Search", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Saved replaces.
        /// </summary>
        public static string Ribbon_Home_Search_StoredReplaces {
            get {
                return ResourceManager.GetString("Ribbon.Home.Search.StoredReplaces", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Saved searches.
        /// </summary>
        public static string Ribbon_Home_Search_StoredSearches {
            get {
                return ResourceManager.GetString("Ribbon.Home.Search.StoredSearches", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Remove empty lines.
        /// </summary>
        public static string Ribbon_Lines_Cleanup_RemoveEmptyLines {
            get {
                return ResourceManager.GetString("Ribbon.Lines.Cleanup.RemoveEmptyLines", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Remove whitespace lines.
        /// </summary>
        public static string Ribbon_Lines_Cleanup_RemoveWhitespaceLines {
            get {
                return ResourceManager.GetString("Ribbon.Lines.Cleanup.RemoveWhitespaceLines", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cleanup.
        /// </summary>
        public static string Ribbon_Lines_Group_Cleanup {
            get {
                return ResourceManager.GetString("Ribbon.Lines.Group.Cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ordering.
        /// </summary>
        public static string Ribbon_Lines_Group_Ordering {
            get {
                return ResourceManager.GetString("Ribbon.Lines.Group.Ordering", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sort ascending.
        /// </summary>
        public static string Ribbon_Lines_Ordering_SortAscending {
            get {
                return ResourceManager.GetString("Ribbon.Lines.Ordering.SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sort descending.
        /// </summary>
        public static string Ribbon_Lines_Ordering_SortDescending {
            get {
                return ResourceManager.GetString("Ribbon.Lines.Ordering.SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Blocks.
        /// </summary>
        public static string Ribbon_Markdown_Blocks {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Blocks", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Blockquote.
        /// </summary>
        public static string Ribbon_Markdown_Blocks_Blockquote {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Blocks.Blockquote", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Source code.
        /// </summary>
        public static string Ribbon_Markdown_Blocks_Code {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Blocks.Code", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ordered list.
        /// </summary>
        public static string Ribbon_Markdown_Blocks_OrderedList {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Blocks.OrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unordered list.
        /// </summary>
        public static string Ribbon_Markdown_Blocks_UnorderedList {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Blocks.UnorderedList", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Headers.
        /// </summary>
        public static string Ribbon_Markdown_Headers {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Headers", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Header 1.
        /// </summary>
        public static string Ribbon_Markdown_Headers_H1 {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Headers.H1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Header 2.
        /// </summary>
        public static string Ribbon_Markdown_Headers_H2 {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Headers.H2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Header 3.
        /// </summary>
        public static string Ribbon_Markdown_Headers_H3 {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Headers.H3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Header 4.
        /// </summary>
        public static string Ribbon_Markdown_Headers_H4 {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Headers.H4", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Header 5.
        /// </summary>
        public static string Ribbon_Markdown_Headers_H5 {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Headers.H5", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Header 6.
        /// </summary>
        public static string Ribbon_Markdown_Headers_H6 {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Headers.H6", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Inline.
        /// </summary>
        public static string Ribbon_Markdown_Inline {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Inline", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Source code.
        /// </summary>
        public static string Ribbon_Markdown_Inline_Code {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Inline.Code", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Emphasis.
        /// </summary>
        public static string Ribbon_Markdown_Inline_Emphasis {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Inline.Emphasis", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Strong.
        /// </summary>
        public static string Ribbon_Markdown_Inline_Strong {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Inline.Strong", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Insert.
        /// </summary>
        public static string Ribbon_Markdown_Insert {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Insert", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Horizontal rule.
        /// </summary>
        public static string Ribbon_Markdown_Insert_Hr {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Insert.Hr", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Link.
        /// </summary>
        public static string Ribbon_Markdown_Insert_Link {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Insert.Link", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Picture.
        /// </summary>
        public static string Ribbon_Markdown_Insert_Picture {
            get {
                return ResourceManager.GetString("Ribbon.Markdown.Insert.Picture", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Home.
        /// </summary>
        public static string Ribbon_Tab_Home {
            get {
                return ResourceManager.GetString("Ribbon.Tab.Home", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lines.
        /// </summary>
        public static string Ribbon_Tab_Lines {
            get {
                return ResourceManager.GetString("Ribbon.Tab.Lines", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Markdown tools.
        /// </summary>
        public static string Ribbon_Tab_MarkdownTools {
            get {
                return ResourceManager.GetString("Ribbon.Tab.MarkdownTools", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Text.
        /// </summary>
        public static string Ribbon_Tab_Text {
            get {
                return ResourceManager.GetString("Ribbon.Tab.Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu View.
        /// </summary>
        public static string Ribbon_Tab_View {
            get {
                return ResourceManager.GetString("Ribbon.Tab.View", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu XML Tools.
        /// </summary>
        public static string Ribbon_Tab_XmlTools {
            get {
                return ResourceManager.GetString("Ribbon.Tab.XmlTools", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Convertion.
        /// </summary>
        public static string Ribbon_Text_Convert {
            get {
                return ResourceManager.GetString("Ribbon.Text.Convert", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Base64.
        /// </summary>
        public static string Ribbon_Text_Convert_Base64 {
            get {
                return ResourceManager.GetString("Ribbon.Text.Convert.Base64", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Base64 Decode.
        /// </summary>
        public static string Ribbon_Text_Convert_Base64_FromBase64 {
            get {
                return ResourceManager.GetString("Ribbon.Text.Convert.Base64.FromBase64", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Base64 Encode.
        /// </summary>
        public static string Ribbon_Text_Convert_Base64_ToBase64 {
            get {
                return ResourceManager.GetString("Ribbon.Text.Convert.Base64.ToBase64", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Escape.
        /// </summary>
        public static string Ribbon_Text_Escape {
            get {
                return ResourceManager.GetString("Ribbon.Text.Escape", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Escape.
        /// </summary>
        public static string Ribbon_Text_Escape_Escape {
            get {
                return ResourceManager.GetString("Ribbon.Text.Escape.Escape", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu HTML entities.
        /// </summary>
        public static string Ribbon_Text_Escape_Htm {
            get {
                return ResourceManager.GetString("Ribbon.Text.Escape.Htm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Decode HTML entities.
        /// </summary>
        public static string Ribbon_Text_Escape_Htm_Decode {
            get {
                return ResourceManager.GetString("Ribbon.Text.Escape.Htm.Decode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Encode HTML entities.
        /// </summary>
        public static string Ribbon_Text_Escape_Htm_Encode {
            get {
                return ResourceManager.GetString("Ribbon.Text.Escape.Htm.Encode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unescape.
        /// </summary>
        public static string Ribbon_Text_Escape_Unescape {
            get {
                return ResourceManager.GetString("Ribbon.Text.Escape.Unescape", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Transformation.
        /// </summary>
        public static string Ribbon_Text_Transform {
            get {
                return ResourceManager.GetString("Ribbon.Text.Transform", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Letter case.
        /// </summary>
        public static string Ribbon_Text_Transform_Case {
            get {
                return ResourceManager.GetString("Ribbon.Text.Transform.Case", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Invert case.
        /// </summary>
        public static string Ribbon_Text_Transform_Case_Invert {
            get {
                return ResourceManager.GetString("Ribbon.Text.Transform.Case.Invert", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lowercase.
        /// </summary>
        public static string Ribbon_Text_Transform_Case_Lowercase {
            get {
                return ResourceManager.GetString("Ribbon.Text.Transform.Case.Lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu As in names.
        /// </summary>
        public static string Ribbon_Text_Transform_Case_Naming {
            get {
                return ResourceManager.GetString("Ribbon.Text.Transform.Case.Naming", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu As in sentence.
        /// </summary>
        public static string Ribbon_Text_Transform_Case_Sentence {
            get {
                return ResourceManager.GetString("Ribbon.Text.Transform.Case.Sentence", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Uppercase.
        /// </summary>
        public static string Ribbon_Text_Transform_Case_Uppercase {
            get {
                return ResourceManager.GetString("Ribbon.Text.Transform.Case.Uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hidden.
        /// </summary>
        public static string Ribbon_View_BottomPanelVisibility_Hidden {
            get {
                return ResourceManager.GetString("Ribbon.View.BottomPanelVisibility.Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Visible.
        /// </summary>
        public static string Ribbon_View_BottomPanelVisibility_Visible {
            get {
                return ResourceManager.GetString("Ribbon.View.BottomPanelVisibility.Visible", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Line numbers.
        /// </summary>
        public static string Ribbon_View_Editor_ShowLineNumbers {
            get {
                return ResourceManager.GetString("Ribbon.View.Editor.ShowLineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Word wrap.
        /// </summary>
        public static string Ribbon_View_Editor_WordWrap {
            get {
                return ResourceManager.GetString("Ribbon.View.Editor.WordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Editor.
        /// </summary>
        public static string Ribbon_View_Group_Editor {
            get {
                return ResourceManager.GetString("Ribbon.View.Group.Editor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Interface.
        /// </summary>
        public static string Ribbon_View_Group_Interface {
            get {
                return ResourceManager.GetString("Ribbon.View.Group.Interface", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Bottom panel.
        /// </summary>
        public static string Ribbon_View_Interface_BottomPanel {
            get {
                return ResourceManager.GetString("Ribbon.View.Interface.BottomPanel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Second view.
        /// </summary>
        public static string Ribbon_View_Interface_ShowSecondaryDocumentTab {
            get {
                return ResourceManager.GetString("Ribbon.View.Interface.ShowSecondaryDocumentTab", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Side panel.
        /// </summary>
        public static string Ribbon_View_Interface_SidePanel {
            get {
                return ResourceManager.GetString("Ribbon.View.Interface.SidePanel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hidden.
        /// </summary>
        public static string Ribbon_View_SidePanelPlacement_Hidden {
            get {
                return ResourceManager.GetString("Ribbon.View.SidePanelPlacement.Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Left.
        /// </summary>
        public static string Ribbon_View_SidePanelPlacement_Left {
            get {
                return ResourceManager.GetString("Ribbon.View.SidePanelPlacement.Left", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Right.
        /// </summary>
        public static string Ribbon_View_SidePanelPlacement_Right {
            get {
                return ResourceManager.GetString("Ribbon.View.SidePanelPlacement.Right", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Syntax highlighting.
        /// </summary>
        public static string Ribbon_View_View_SyntaxHighlighting {
            get {
                return ResourceManager.GetString("Ribbon.View.View.SyntaxHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Format XML.
        /// </summary>
        public static string Ribbon_XmlTools_Formatting_Format {
            get {
                return ResourceManager.GetString("Ribbon.XmlTools.Formatting.Format", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Formatting.
        /// </summary>
        public static string Ribbon_XmlTools_Group_Formatting {
            get {
                return ResourceManager.GetString("Ribbon.XmlTools.Group.Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Transform.
        /// </summary>
        public static string Ribbon_XmlTools_Group_Transform {
            get {
                return ResourceManager.GetString("Ribbon.XmlTools.Group.Transform", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu XSLT transform.
        /// </summary>
        public static string Ribbon_XmlTools_Transform_XSLT {
            get {
                return ResourceManager.GetString("Ribbon.XmlTools.Transform.XSLT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Replace.
        /// </summary>
        public static string Search_ReplaceTitle {
            get {
                return ResourceManager.GetString("Search.ReplaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search.
        /// </summary>
        public static string Search_SearchTitle {
            get {
                return ResourceManager.GetString("Search.SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Case sensitive.
        /// </summary>
        public static string SearchWindow_CaseSensitive {
            get {
                return ResourceManager.GetString("SearchWindow.CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Close.
        /// </summary>
        public static string SearchWindow_Close {
            get {
                return ResourceManager.GetString("SearchWindow.Close", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Count occurrences.
        /// </summary>
        public static string SearchWindow_CountOccurrences {
            get {
                return ResourceManager.GetString("SearchWindow.CountOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu File mask.
        /// </summary>
        public static string SearchWindow_FileMask {
            get {
                return ResourceManager.GetString("SearchWindow.FileMask", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Find next.
        /// </summary>
        public static string SearchWindow_FindNext {
            get {
                return ResourceManager.GetString("SearchWindow.FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu In selection.
        /// </summary>
        public static string SearchWindow_InSelection {
            get {
                return ResourceManager.GetString("SearchWindow.InSelection", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Directory.
        /// </summary>
        public static string SearchWindow_Location {
            get {
                return ResourceManager.GetString("SearchWindow.Location", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Only full words.
        /// </summary>
        public static string SearchWindow_OnlyFullWords {
            get {
                return ResourceManager.GetString("SearchWindow.OnlyFullWords", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Replace.
        /// </summary>
        public static string SearchWindow_Replace {
            get {
                return ResourceManager.GetString("SearchWindow.Replace", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Replace all.
        /// </summary>
        public static string SearchWindow_ReplaceAll {
            get {
                return ResourceManager.GetString("SearchWindow.ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Replace options.
        /// </summary>
        public static string SearchWindow_ReplaceOptions {
            get {
                return ResourceManager.GetString("SearchWindow.ReplaceOptions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Replace.
        /// </summary>
        public static string SearchWindow_ReplaceTab {
            get {
                return ResourceManager.GetString("SearchWindow.ReplaceTab", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Replace with.
        /// </summary>
        public static string SearchWindow_ReplaceWith {
            get {
                return ResourceManager.GetString("SearchWindow.ReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search.
        /// </summary>
        public static string SearchWindow_Search {
            get {
                return ResourceManager.GetString("SearchWindow.Search", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search backwards.
        /// </summary>
        public static string SearchWindow_SearchBackwards {
            get {
                return ResourceManager.GetString("SearchWindow.SearchBackwards", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Text to search.
        /// </summary>
        public static string SearchWindow_SearchedText {
            get {
                return ResourceManager.GetString("SearchWindow.SearchedText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Find in files.
        /// </summary>
        public static string SearchWindow_SearchInFilesTab {
            get {
                return ResourceManager.GetString("SearchWindow.SearchInFilesTab", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search mode.
        /// </summary>
        public static string SearchWindow_SearchMode {
            get {
                return ResourceManager.GetString("SearchWindow.SearchMode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Extended (\n, \t etc.).
        /// </summary>
        public static string SearchWindow_SearchModeExtended {
            get {
                return ResourceManager.GetString("SearchWindow.SearchModeExtended", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Normal.
        /// </summary>
        public static string SearchWindow_SearchModeNormal {
            get {
                return ResourceManager.GetString("SearchWindow.SearchModeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Regular expressions.
        /// </summary>
        public static string SearchWindow_SearchModeRegex {
            get {
                return ResourceManager.GetString("SearchWindow.SearchModeRegex", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search options.
        /// </summary>
        public static string SearchWindow_SearchOptions {
            get {
                return ResourceManager.GetString("SearchWindow.SearchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search.
        /// </summary>
        public static string SearchWindow_SearchTab {
            get {
                return ResourceManager.GetString("SearchWindow.SearchTab", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show summary.
        /// </summary>
        public static string SearchWindow_ShowSummary {
            get {
                return ResourceManager.GetString("SearchWindow.ShowSummary", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search.
        /// </summary>
        public static string SearchWindow_Title {
            get {
                return ResourceManager.GetString("SearchWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu (none).
        /// </summary>
        public static string SyntaxHighlighting_None {
            get {
                return ResourceManager.GetString("SyntaxHighlighting.None", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit in Dev.Editor.
        /// </summary>
        public static string SystemIntegration_OpenInDevEditor {
            get {
                return ResourceManager.GetString("SystemIntegration.OpenInDevEditor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Copy.
        /// </summary>
        public static string TextEditor_ContextMenu_Copy {
            get {
                return ResourceManager.GetString("TextEditor.ContextMenu.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cut.
        /// </summary>
        public static string TextEditor_ContextMenu_Cut {
            get {
                return ResourceManager.GetString("TextEditor.ContextMenu.Cut", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Paste.
        /// </summary>
        public static string TextEditor_ContextMenu_Paste {
            get {
                return ResourceManager.GetString("TextEditor.ContextMenu.Paste", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SPLIT.
        /// </summary>
        public static string TextEditor_Footer_Split {
            get {
                return ResourceManager.GetString("TextEditor.Footer.Split", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Binary definitions.
        /// </summary>
        public static string Tool_BinDefinitions_Title {
            get {
                return ResourceManager.GetString("Tool.BinDefinitions.Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open.
        /// </summary>
        public static string Tool_Explorer_Files_Open {
            get {
                return ResourceManager.GetString("Tool.Explorer.Files.Open", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open in hex editor.
        /// </summary>
        public static string Tool_Explorer_Files_OpenInHexeditor {
            get {
                return ResourceManager.GetString("Tool.Explorer.Files.OpenInHexeditor", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Show in Windows Explorer.
        /// </summary>
        public static string Tool_Explorer_Files_ShowInExplorer {
            get {
                return ResourceManager.GetString("Tool.Explorer.Files.ShowInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open in Windows Explorer.
        /// </summary>
        public static string Tool_Explorer_Folders_OpenInExplorer {
            get {
                return ResourceManager.GetString("Tool.Explorer.Folders.OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Files.
        /// </summary>
        public static string Tool_Explorer_Title {
            get {
                return ResourceManager.GetString("Tool.Explorer.Title", resourceCulture);
            }
        }
    }
}
