//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev.Editor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dev.Editor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // The following example binary definition processes a bitmap file (.BMP)
        ///// and provides information decoded from the bitmap header.
        ///
        ///struct BmpHeader 
        ///{
        ///    char[2] descriptor;
        ///    int bmpSizeInBytes;
        ///    short reserved1;
        ///    short reserved2;
        ///    int dataOffset;
        ///};
        ///
        ///enum DibHeaderType : byte 
        ///{
        /// BITMAPCOREHEADER = 1u,
        /// OS21XBITMAPHEADER = 2u,
        /// OS22XBITMAPHEADER_V1 = 3u,
        /// OS22XBITMAPHEADER_V2 = 4u,
        /// BITMAPINFOHEADER = 5u,
        /// BITMAPV2INFOHEADER = 6u,
        /// BITMAPV3INFOHEADER = 7u,
        /// BITMAPV4HEA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BinDefinitionSample {
            get {
                return ResourceManager.GetString("BinDefinitionSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string BlankDocName {
            get {
                return ResourceManager.GetString("BlankDocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string BlankDocumentName {
            get {
                return ResourceManager.GetString("BlankDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string BottomTool_Messages_Title {
            get {
                return ResourceManager.GetString("BottomTool.Messages.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax highlighting {0}.
        /// </summary>
        public static string Command_SetHighlighting {
            get {
                return ResourceManager.GetString("Command.SetHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        public static string Configuration_Behavior {
            get {
                return ResourceManager.GetString("Configuration.Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing behavior.
        /// </summary>
        public static string Configuration_Behavior_ClosingBehavior {
            get {
                return ResourceManager.GetString("Configuration.Behavior.ClosingBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose, how application should behave when closing:.
        /// </summary>
        public static string Configuration_Behavior_ClosingBehavior_Comment {
            get {
                return ResourceManager.GetString("Configuration.Behavior.ClosingBehavior.Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluent.
        /// </summary>
        public static string Configuration_Behavior_ClosingBehavior_Fluent {
            get {
                return ResourceManager.GetString("Configuration.Behavior.ClosingBehavior.Fluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev.Editor will store all open documents and restore them on startup (including unsaved changes).
        /// </summary>
        public static string Configuration_Behavior_ClosingBehavior_Fluent_Comment {
            get {
                return ResourceManager.GetString("Configuration.Behavior.ClosingBehavior.Fluent.Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string Configuration_Behavior_ClosingBehavior_Standard {
            get {
                return ResourceManager.GetString("Configuration.Behavior.ClosingBehavior.Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev.Editor will close all documents upon closing and start with blank new document.
        /// </summary>
        public static string Configuration_Behavior_ClosingBehavior_Standard_Comment {
            get {
                return ResourceManager.GetString("Configuration.Behavior.ClosingBehavior.Standard.Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Configuration_System {
            get {
                return ResourceManager.GetString("Configuration.System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable integration.
        /// </summary>
        public static string Configuration_System_Integration_Disable {
            get {
                return ResourceManager.GetString("Configuration.System.Integration.Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration is disabled.
        /// </summary>
        public static string Configuration_System_Integration_Disabled {
            get {
                return ResourceManager.GetString("Configuration.System.Integration.Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable integration.
        /// </summary>
        public static string Configuration_System_Integration_Enable {
            get {
                return ResourceManager.GetString("Configuration.System.Integration.Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration is enabled.
        /// </summary>
        public static string Configuration_System_Integration_Enabled {
            get {
                return ResourceManager.GetString("Configuration.System.Integration.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System context menu integration.
        /// </summary>
        public static string Configuration_System_IntegrationHeader {
            get {
                return ResourceManager.GetString("Configuration.System.IntegrationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration state.
        /// </summary>
        public static string Configuration_System_IntegrationState {
            get {
                return ResourceManager.GetString("Configuration.System.IntegrationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration_Title {
            get {
                return ResourceManager.GetString("Configuration.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev.Editor.
        /// </summary>
        public static string DefaultDialogTitle {
            get {
                return ResourceManager.GetString("DefaultDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        public static string DefaultFilter {
            get {
                return ResourceManager.GetString("DefaultFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev.Editor.
        /// </summary>
        public static string DefaultMessageboxTitle {
            get {
                return ResourceManager.GetString("DefaultMessageboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary definition.
        /// </summary>
        public static string Dialog_BinDefinition_Title {
            get {
                return ResourceManager.GetString("Dialog.BinDefinition.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Dialog_Name_Name {
            get {
                return ResourceManager.GetString("Dialog.Name.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored search.
        /// </summary>
        public static string Dialog_StoredSearch_Title {
            get {
                return ResourceManager.GetString("Dialog.StoredSearch.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSLT sheets (*.xsl)|*.xsl.
        /// </summary>
        public static string Filter_Xslt {
            get {
                return ResourceManager.GetString("Filter.Xslt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform assignment to {0}. Reason:
        ///{1}.
        /// </summary>
        public static string Message_AnalysisError_CannotAssign {
            get {
                return ResourceManager.GetString("Message.AnalysisError.CannotAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add evaluated field {0}. Reason:
        ///{1}.
        /// </summary>
        public static string Message_AnalysisError_CannotShow {
            get {
                return ResourceManager.GetString("Message.AnalysisError.CannotShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read field {0}. Reason:
        ///{1}.
        /// </summary>
        public static string Message_AnalysisError_FailedToReadField {
            get {
                return ResourceManager.GetString("Message.AnalysisError.FailedToReadField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read struct field {0}. Reason:
        ///{1}.
        /// </summary>
        public static string Message_AnalysisError_FailedToReadStruct {
            get {
                return ResourceManager.GetString("Message.AnalysisError.FailedToReadStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read struct array field {0}. Reason:
        ///{1}.
        /// </summary>
        public static string Message_AnalysisError_FailedToReadStructArray {
            get {
                return ResourceManager.GetString("Message.AnalysisError.FailedToReadStructArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to skip bytes. Reason:
        ///{0}.
        /// </summary>
        public static string Message_AnalysisError_FailedToSkip {
            get {
                return ResourceManager.GetString("Message.AnalysisError.FailedToSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition in if statement must evaluate to bool value!.
        /// </summary>
        public static string Message_AnalysisError_InvalidIfCondition {
            get {
                return ResourceManager.GetString("Message.AnalysisError.InvalidIfCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of file!.
        /// </summary>
        public static string Message_AnalysisError_UnexpectedEndOfStream {
            get {
                return ResourceManager.GetString("Message.AnalysisError.UnexpectedEndOfStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete binary definition {0}?.
        /// </summary>
        public static string Message_BinDefinitionDeleteConfirmation {
            get {
                return ResourceManager.GetString("Message.BinDefinitionDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add binary definition, error: {0}.
        /// </summary>
        public static string Message_CannotAddBinDefinition {
            get {
                return ResourceManager.GetString("Message.CannotAddBinDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot format - XML is invalid..
        /// </summary>
        public static string Message_CannotFormatInvalidXml {
            get {
                return ResourceManager.GetString("Message.CannotFormatInvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open binary file. See Messages window for details..
        /// </summary>
        public static string Message_CannotOpenBinFile {
            get {
                return ResourceManager.GetString("Message.CannotOpenBinFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open file {0}. Error: {1}.
        /// </summary>
        public static string Message_CannotOpenFile {
            get {
                return ResourceManager.GetString("Message.CannotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot restore file {0}. Error message: {1}.
        /// </summary>
        public static string Message_CannotRestoreFile {
            get {
                return ResourceManager.GetString("Message.CannotRestoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save configuration file. Are you sure you want to exit?.
        /// </summary>
        public static string Message_CannotSaveConfiguration {
            get {
                return ResourceManager.GetString("Message.CannotSaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save file {0}. Error: {1}.
        /// </summary>
        public static string Message_CannotSaveFile {
            get {
                return ResourceManager.GetString("Message.CannotSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot transform XML file with XSLT. See Messages window for details..
        /// </summary>
        public static string Message_CannotTransformXslt {
            get {
                return ResourceManager.GetString("Message.CannotTransformXslt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access member {0} of field {1}..
        /// </summary>
        public static string Message_EvalError_CannotAccessMember {
            get {
                return ResourceManager.GetString("Message.EvalError.CannotAccessMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find identifier {0} in current scope..
        /// </summary>
        public static string Message_EvalError_CannotFindIdentifier {
            get {
                return ResourceManager.GetString("Message.EvalError.CannotFindIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum {0} does not contain member {1}..
        /// </summary>
        public static string Message_EvalError_EnumDoesNotContainMember {
            get {
                return ResourceManager.GetString("Message.EvalError.EnumDoesNotContainMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to evaluate binary operator. Reason:
        ///{0}.
        /// </summary>
        public static string Message_EvalError_FailedToEvalBinaryOperator {
            get {
                return ResourceManager.GetString("Message.EvalError.FailedToEvalBinaryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to evaluate expression. Reason:
        ///{0}.
        /// </summary>
        public static string Message_EvalError_FailedToEvalExpression {
            get {
                return ResourceManager.GetString("Message.EvalError.FailedToEvalExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier {0} does not point to a value-type field..
        /// </summary>
        public static string Message_EvalError_MemberIsNotValue {
            get {
                return ResourceManager.GetString("Message.EvalError.MemberIsNotValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save document {0} before closing?.
        /// </summary>
        public static string Message_FileNotSaved {
            get {
                return ResourceManager.GetString("Message.FileNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Base64 string!.
        /// </summary>
        public static string Message_InvalidBase64String {
            get {
                return ResourceManager.GetString("Message.InvalidBase64String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid search pattern!.
        /// </summary>
        public static string Message_InvalidSearchPattern {
            get {
                return ResourceManager.GetString("Message.InvalidSearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find any occurrences of entered text..
        /// </summary>
        public static string Message_NoMorePatternsFound {
            get {
                return ResourceManager.GetString("Message.NoMorePatternsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced occurrences: {0}..
        /// </summary>
        public static string Message_ReplacedOccurrences {
            get {
                return ResourceManager.GetString("Message.ReplacedOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search reached beginning of the file. Do you want to continue from the end?.
        /// </summary>
        public static string Message_SearchReachedBeginning {
            get {
                return ResourceManager.GetString("Message.SearchReachedBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search reached end of the file. Do you want to continue from the beginning?.
        /// </summary>
        public static string Message_SearchReachedEnd {
            get {
                return ResourceManager.GetString("Message.SearchReachedEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete stored search &quot;{0}&quot;?.
        /// </summary>
        public static string Message_StoredSearchDeleteConfirmation {
            get {
                return ResourceManager.GetString("Message.StoredSearchDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find type name {0} !.
        /// </summary>
        public static string Message_SyntaxError_CannotFindTypeName {
            get {
                return ResourceManager.GetString("Message.SyntaxError.CannotFindTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum item with value {0} already exists!.
        /// </summary>
        public static string Message_SyntaxError_EnumItemValueDuplicated {
            get {
                return ResourceManager.GetString("Message.SyntaxError.EnumItemValueDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process definition!.
        /// </summary>
        public static string Message_SyntaxError_FailedToProcessDefinition {
            get {
                return ResourceManager.GetString("Message.SyntaxError.FailedToProcessDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field with name {0} already exists!.
        /// </summary>
        public static string Message_SyntaxError_FieldAlreadyExists {
            get {
                return ResourceManager.GetString("Message.SyntaxError.FieldAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum member {0} value ({1}) is outside underlying integer type range ({2})!.
        /// </summary>
        public static string Message_SyntaxError_IntegerValueOutsideRange {
            get {
                return ResourceManager.GetString("Message.SyntaxError.IntegerValueOutsideRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid floating point value: {0} !.
        /// </summary>
        public static string Message_SyntaxError_InvalidFloatNumber {
            get {
                return ResourceManager.GetString("Message.SyntaxError.InvalidFloatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid integer value: {0} !.
        /// </summary>
        public static string Message_SyntaxError_InvalidIntegerValue {
            get {
                return ResourceManager.GetString("Message.SyntaxError.InvalidIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed-type enum should contain only signed int values!.
        /// </summary>
        public static string Message_SyntaxError_InvalidSignedEnumItem {
            get {
                return ResourceManager.GetString("Message.SyntaxError.InvalidSignedEnumItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsigned-type enum should contain only unsigned int values (with suffix &quot;u&quot;)!.
        /// </summary>
        public static string Message_SyntaxError_InvalidUnsignedEnumItem {
            get {
                return ResourceManager.GetString("Message.SyntaxError.InvalidUnsignedEnumItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid unsigned integer value: {0}!.
        /// </summary>
        public static string Message_SyntaxError_InvalidUnsignedIntegerValue {
            get {
                return ResourceManager.GetString("Message.SyntaxError.InvalidUnsignedIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct with name {0} already exists!.
        /// </summary>
        public static string Message_SyntaxError_StructureAlreadyExists {
            get {
                return ResourceManager.GetString("Message.SyntaxError.StructureAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error in definition: {0}.
        /// </summary>
        public static string Message_SyntaxError_SyntaxError {
            get {
                return ResourceManager.GetString("Message.SyntaxError.SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click binary definition to open binary file and analyze it..
        /// </summary>
        public static string Message_UseSidePanelToOpenBinFile {
            get {
                return ResourceManager.GetString("Message.UseSidePanelToOpenBinFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Messages_Code {
            get {
                return ResourceManager.GetString("Messages.Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string Messages_Column {
            get {
                return ResourceManager.GetString("Messages.Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Messages_File {
            get {
                return ResourceManager.GetString("Messages.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Messages_Message {
            get {
                return ResourceManager.GetString("Messages.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Messages_Row {
            get {
                return ResourceManager.GetString("Messages.Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        public static string Messages_Severity {
            get {
                return ResourceManager.GetString("Messages.Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        public static string NameDialog_GroupBoxHeader {
            get {
                return ResourceManager.GetString("NameDialog.GroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameDialog_Label {
            get {
                return ResourceManager.GetString("NameDialog.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        public static string NameDialog_Title {
            get {
                return ResourceManager.GetString("NameDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string NavigationPopup_Header {
            get {
                return ResourceManager.GetString("NavigationPopup.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This is Dev.Editor&apos;s {0} binary file definition.
        ///.
        /// </summary>
        public static string NewBinaryDefinitionContents {
            get {
                return ResourceManager.GetString("NewBinaryDefinitionContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open binary file {0}.
        /// </summary>
        public static string OpenBinaryFile_Title {
            get {
                return ResourceManager.GetString("OpenBinaryFile.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        public static string Ribbon_ContextGroup_Xml {
            get {
                return ResourceManager.GetString("Ribbon.ContextGroup.Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Ribbon_Home_Edit_Copy {
            get {
                return ResourceManager.GetString("Ribbon.Home.Edit.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Ribbon_Home_Edit_Cut {
            get {
                return ResourceManager.GetString("Ribbon.Home.Edit.Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Ribbon_Home_Edit_Paste {
            get {
                return ResourceManager.GetString("Ribbon.Home.Edit.Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Ribbon_Home_Edit_Redo {
            get {
                return ResourceManager.GetString("Ribbon.Home.Edit.Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Ribbon_Home_Edit_Undo {
            get {
                return ResourceManager.GetString("Ribbon.Home.Edit.Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Ribbon_Home_File_New {
            get {
                return ResourceManager.GetString("Ribbon.Home.File.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New hex editor.
        /// </summary>
        public static string Ribbon_Home_File_NewHex {
            get {
                return ResourceManager.GetString("Ribbon.Home.File.NewHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Ribbon_Home_File_Open {
            get {
                return ResourceManager.GetString("Ribbon.Home.File.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open binary file.
        /// </summary>
        public static string Ribbon_Home_File_OpenBin {
            get {
                return ResourceManager.GetString("Ribbon.Home.File.OpenBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in hex editor.
        /// </summary>
        public static string Ribbon_Home_File_OpenHex {
            get {
                return ResourceManager.GetString("Ribbon.Home.File.OpenHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Ribbon_Home_File_Save {
            get {
                return ResourceManager.GetString("Ribbon.Home.File.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string Ribbon_Home_File_SaveAs {
            get {
                return ResourceManager.GetString("Ribbon.Home.File.SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Ribbon_Home_Group_Edit {
            get {
                return ResourceManager.GetString("Ribbon.Home.Group.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Ribbon_Home_Group_File {
            get {
                return ResourceManager.GetString("Ribbon.Home.Group.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string Ribbon_Home_Group_Navigation {
            get {
                return ResourceManager.GetString("Ribbon.Home.Group.Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Ribbon_Home_Group_Search {
            get {
                return ResourceManager.GetString("Ribbon.Home.Group.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string Ribbon_Home_Navigation_Navigate {
            get {
                return ResourceManager.GetString("Ribbon.Home.Navigation.Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find next.
        /// </summary>
        public static string Ribbon_Home_Search_FindNext {
            get {
                return ResourceManager.GetString("Ribbon.Home.Search.FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Ribbon_Home_Search_Replace {
            get {
                return ResourceManager.GetString("Ribbon.Home.Search.Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Ribbon_Home_Search_Search {
            get {
                return ResourceManager.GetString("Ribbon.Home.Search.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove empty lines.
        /// </summary>
        public static string Ribbon_Lines_Cleanup_RemoveEmptyLines {
            get {
                return ResourceManager.GetString("Ribbon.Lines.Cleanup.RemoveEmptyLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove whitespace lines.
        /// </summary>
        public static string Ribbon_Lines_Cleanup_RemoveWhitespaceLines {
            get {
                return ResourceManager.GetString("Ribbon.Lines.Cleanup.RemoveWhitespaceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup.
        /// </summary>
        public static string Ribbon_Lines_Group_Cleanup {
            get {
                return ResourceManager.GetString("Ribbon.Lines.Group.Cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordering.
        /// </summary>
        public static string Ribbon_Lines_Group_Ordering {
            get {
                return ResourceManager.GetString("Ribbon.Lines.Group.Ordering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort ascending.
        /// </summary>
        public static string Ribbon_Lines_Ordering_SortAscending {
            get {
                return ResourceManager.GetString("Ribbon.Lines.Ordering.SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort descending.
        /// </summary>
        public static string Ribbon_Lines_Ordering_SortDescending {
            get {
                return ResourceManager.GetString("Ribbon.Lines.Ordering.SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Ribbon_Tab_Home {
            get {
                return ResourceManager.GetString("Ribbon.Tab.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        public static string Ribbon_Tab_Lines {
            get {
                return ResourceManager.GetString("Ribbon.Tab.Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Ribbon_Tab_Text {
            get {
                return ResourceManager.GetString("Ribbon.Tab.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Ribbon_Tab_View {
            get {
                return ResourceManager.GetString("Ribbon.Tab.View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Tools.
        /// </summary>
        public static string Ribbon_Tab_XmlTools {
            get {
                return ResourceManager.GetString("Ribbon.Tab.XmlTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertion.
        /// </summary>
        public static string Ribbon_Text_Convert {
            get {
                return ResourceManager.GetString("Ribbon.Text.Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base64.
        /// </summary>
        public static string Ribbon_Text_Convert_Base64 {
            get {
                return ResourceManager.GetString("Ribbon.Text.Convert.Base64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base64 Decode.
        /// </summary>
        public static string Ribbon_Text_Convert_Base64_FromBase64 {
            get {
                return ResourceManager.GetString("Ribbon.Text.Convert.Base64.FromBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base64 Encode.
        /// </summary>
        public static string Ribbon_Text_Convert_Base64_ToBase64 {
            get {
                return ResourceManager.GetString("Ribbon.Text.Convert.Base64.ToBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter case.
        /// </summary>
        public static string Ribbon_Text_Convert_Case {
            get {
                return ResourceManager.GetString("Ribbon.Text.Convert.Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert case.
        /// </summary>
        public static string Ribbon_Text_Convert_Case_Invert {
            get {
                return ResourceManager.GetString("Ribbon.Text.Convert.Case.Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowercase.
        /// </summary>
        public static string Ribbon_Text_Convert_Case_Lowercase {
            get {
                return ResourceManager.GetString("Ribbon.Text.Convert.Case.Lowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As in names.
        /// </summary>
        public static string Ribbon_Text_Convert_Case_Naming {
            get {
                return ResourceManager.GetString("Ribbon.Text.Convert.Case.Naming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As in sentence.
        /// </summary>
        public static string Ribbon_Text_Convert_Case_Sentence {
            get {
                return ResourceManager.GetString("Ribbon.Text.Convert.Case.Sentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppercase.
        /// </summary>
        public static string Ribbon_Text_Convert_Case_Uppercase {
            get {
                return ResourceManager.GetString("Ribbon.Text.Convert.Case.Uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string Ribbon_View_BottomPanelVisibility_Hidden {
            get {
                return ResourceManager.GetString("Ribbon.View.BottomPanelVisibility.Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string Ribbon_View_BottomPanelVisibility_Visible {
            get {
                return ResourceManager.GetString("Ribbon.View.BottomPanelVisibility.Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line numbers.
        /// </summary>
        public static string Ribbon_View_Editor_ShowLineNumbers {
            get {
                return ResourceManager.GetString("Ribbon.View.Editor.ShowLineNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word wrap.
        /// </summary>
        public static string Ribbon_View_Editor_WordWrap {
            get {
                return ResourceManager.GetString("Ribbon.View.Editor.WordWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string Ribbon_View_Group_Editor {
            get {
                return ResourceManager.GetString("Ribbon.View.Group.Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        public static string Ribbon_View_Group_Interface {
            get {
                return ResourceManager.GetString("Ribbon.View.Group.Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom panel.
        /// </summary>
        public static string Ribbon_View_Interface_BottomPanel {
            get {
                return ResourceManager.GetString("Ribbon.View.Interface.BottomPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side panel.
        /// </summary>
        public static string Ribbon_View_Interface_SidePanel {
            get {
                return ResourceManager.GetString("Ribbon.View.Interface.SidePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string Ribbon_View_SidePanelPlacement_Hidden {
            get {
                return ResourceManager.GetString("Ribbon.View.SidePanelPlacement.Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Ribbon_View_SidePanelPlacement_Left {
            get {
                return ResourceManager.GetString("Ribbon.View.SidePanelPlacement.Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Ribbon_View_SidePanelPlacement_Right {
            get {
                return ResourceManager.GetString("Ribbon.View.SidePanelPlacement.Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax highlighting.
        /// </summary>
        public static string Ribbon_View_View_SyntaxHighlighting {
            get {
                return ResourceManager.GetString("Ribbon.View.View.SyntaxHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format XML.
        /// </summary>
        public static string Ribbon_XmlTools_Formatting_Format {
            get {
                return ResourceManager.GetString("Ribbon.XmlTools.Formatting.Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting.
        /// </summary>
        public static string Ribbon_XmlTools_Group_Formatting {
            get {
                return ResourceManager.GetString("Ribbon.XmlTools.Group.Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform.
        /// </summary>
        public static string Ribbon_XmlTools_Group_Transform {
            get {
                return ResourceManager.GetString("Ribbon.XmlTools.Group.Transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSLT transform.
        /// </summary>
        public static string Ribbon_XmlTools_Transform_XSLT {
            get {
                return ResourceManager.GetString("Ribbon.XmlTools.Transform.XSLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Search_ReplaceTitle {
            get {
                return ResourceManager.GetString("Search.ReplaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_SearchTitle {
            get {
                return ResourceManager.GetString("Search.SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case sensitive.
        /// </summary>
        public static string SearchWindow_CaseSensitive {
            get {
                return ResourceManager.GetString("SearchWindow.CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SearchWindow_Close {
            get {
                return ResourceManager.GetString("SearchWindow.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find next.
        /// </summary>
        public static string SearchWindow_FindNext {
            get {
                return ResourceManager.GetString("SearchWindow.FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In selection.
        /// </summary>
        public static string SearchWindow_InSelection {
            get {
                return ResourceManager.GetString("SearchWindow.InSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only full words.
        /// </summary>
        public static string SearchWindow_OnlyFullWords {
            get {
                return ResourceManager.GetString("SearchWindow.OnlyFullWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string SearchWindow_Replace {
            get {
                return ResourceManager.GetString("SearchWindow.Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace all.
        /// </summary>
        public static string SearchWindow_ReplaceAll {
            get {
                return ResourceManager.GetString("SearchWindow.ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace options.
        /// </summary>
        public static string SearchWindow_ReplaceOptions {
            get {
                return ResourceManager.GetString("SearchWindow.ReplaceOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string SearchWindow_ReplaceTab {
            get {
                return ResourceManager.GetString("SearchWindow.ReplaceTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with.
        /// </summary>
        public static string SearchWindow_ReplaceWith {
            get {
                return ResourceManager.GetString("SearchWindow.ReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchWindow_Search {
            get {
                return ResourceManager.GetString("SearchWindow.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search backwards.
        /// </summary>
        public static string SearchWindow_SearchBackwards {
            get {
                return ResourceManager.GetString("SearchWindow.SearchBackwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to search.
        /// </summary>
        public static string SearchWindow_SearchedText {
            get {
                return ResourceManager.GetString("SearchWindow.SearchedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search mode.
        /// </summary>
        public static string SearchWindow_SearchMode {
            get {
                return ResourceManager.GetString("SearchWindow.SearchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended (\n, \t etc.).
        /// </summary>
        public static string SearchWindow_SearchModeExtended {
            get {
                return ResourceManager.GetString("SearchWindow.SearchModeExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string SearchWindow_SearchModeNormal {
            get {
                return ResourceManager.GetString("SearchWindow.SearchModeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expressions.
        /// </summary>
        public static string SearchWindow_SearchModeRegex {
            get {
                return ResourceManager.GetString("SearchWindow.SearchModeRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search options.
        /// </summary>
        public static string SearchWindow_SearchOptions {
            get {
                return ResourceManager.GetString("SearchWindow.SearchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchWindow_SearchTab {
            get {
                return ResourceManager.GetString("SearchWindow.SearchTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show summary.
        /// </summary>
        public static string SearchWindow_ShowSummary {
            get {
                return ResourceManager.GetString("SearchWindow.ShowSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchWindow_Title {
            get {
                return ResourceManager.GetString("SearchWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string SyntaxHighlighting_None {
            get {
                return ResourceManager.GetString("SyntaxHighlighting.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit in Dev.Editor.
        /// </summary>
        public static string SystemIntegration_OpenInDevEditor {
            get {
                return ResourceManager.GetString("SystemIntegration.OpenInDevEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string TextEditor_ContextMenu_Copy {
            get {
                return ResourceManager.GetString("TextEditor.ContextMenu.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string TextEditor_ContextMenu_Cut {
            get {
                return ResourceManager.GetString("TextEditor.ContextMenu.Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string TextEditor_ContextMenu_Paste {
            get {
                return ResourceManager.GetString("TextEditor.ContextMenu.Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary definitions.
        /// </summary>
        public static string Tool_BinDefinitions_Title {
            get {
                return ResourceManager.GetString("Tool.BinDefinitions.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Windows Explorer.
        /// </summary>
        public static string Tool_Explorer_Files_ShowInExplorer {
            get {
                return ResourceManager.GetString("Tool.Explorer.Files.ShowInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Windows Explorer.
        /// </summary>
        public static string Tool_Explorer_Folders_OpenInExplorer {
            get {
                return ResourceManager.GetString("Tool.Explorer.Folders.OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Tool_Explorer_Title {
            get {
                return ResourceManager.GetString("Tool.Explorer.Title", resourceCulture);
            }
        }
    }
}
