//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dev.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Document.
        /// </summary>
        public static string BlankDocName {
            get {
                return ResourceManager.GetString("BlankDocName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dev.Editor.
        /// </summary>
        public static string DefaultDialogTitle {
            get {
                return ResourceManager.GetString("DefaultDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu All files (*.*)|*.*.
        /// </summary>
        public static string DefaultFilter {
            get {
                return ResourceManager.GetString("DefaultFilter", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Copy.
        /// </summary>
        public static string Ribbon_Edit_Copy {
            get {
                return ResourceManager.GetString("Ribbon.Edit.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cut.
        /// </summary>
        public static string Ribbon_Edit_Cut {
            get {
                return ResourceManager.GetString("Ribbon.Edit.Cut", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Paste.
        /// </summary>
        public static string Ribbon_Edit_Paste {
            get {
                return ResourceManager.GetString("Ribbon.Edit.Paste", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Redo.
        /// </summary>
        public static string Ribbon_Edit_Redo {
            get {
                return ResourceManager.GetString("Ribbon.Edit.Redo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Undo.
        /// </summary>
        public static string Ribbon_Edit_Undo {
            get {
                return ResourceManager.GetString("Ribbon.Edit.Undo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New.
        /// </summary>
        public static string Ribbon_File_New {
            get {
                return ResourceManager.GetString("Ribbon.File.New", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open.
        /// </summary>
        public static string Ribbon_File_Open {
            get {
                return ResourceManager.GetString("Ribbon.File.Open", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save.
        /// </summary>
        public static string Ribbon_File_Save {
            get {
                return ResourceManager.GetString("Ribbon.File.Save", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save as.
        /// </summary>
        public static string Ribbon_File_SaveAs {
            get {
                return ResourceManager.GetString("Ribbon.File.SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Edit.
        /// </summary>
        public static string Ribbon_Group_Edit {
            get {
                return ResourceManager.GetString("Ribbon.Group.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu File.
        /// </summary>
        public static string Ribbon_Group_File {
            get {
                return ResourceManager.GetString("Ribbon.Group.File", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search.
        /// </summary>
        public static string Ribbon_Group_Search {
            get {
                return ResourceManager.GetString("Ribbon.Group.Search", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Find next.
        /// </summary>
        public static string Ribbon_Search_FindNext {
            get {
                return ResourceManager.GetString("Ribbon.Search.FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Replace.
        /// </summary>
        public static string Ribbon_Search_Replace {
            get {
                return ResourceManager.GetString("Ribbon.Search.Replace", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search.
        /// </summary>
        public static string Ribbon_Search_Search {
            get {
                return ResourceManager.GetString("Ribbon.Search.Search", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Home.
        /// </summary>
        public static string Ribbon_Tab_Home {
            get {
                return ResourceManager.GetString("Ribbon.Tab.Home", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Case sensitive.
        /// </summary>
        public static string SearchWindow_CaseSensitive {
            get {
                return ResourceManager.GetString("SearchWindow.CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Close.
        /// </summary>
        public static string SearchWindow_Close {
            get {
                return ResourceManager.GetString("SearchWindow.Close", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Find next.
        /// </summary>
        public static string SearchWindow_FindNext {
            get {
                return ResourceManager.GetString("SearchWindow.FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Only full words.
        /// </summary>
        public static string SearchWindow_OnlyFullWords {
            get {
                return ResourceManager.GetString("SearchWindow.OnlyFullWords", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Replace.
        /// </summary>
        public static string SearchWindow_Replace {
            get {
                return ResourceManager.GetString("SearchWindow.Replace", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Replace all.
        /// </summary>
        public static string SearchWindow_ReplaceAll {
            get {
                return ResourceManager.GetString("SearchWindow.ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Replace.
        /// </summary>
        public static string SearchWindow_ReplaceTab {
            get {
                return ResourceManager.GetString("SearchWindow.ReplaceTab", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Replace with.
        /// </summary>
        public static string SearchWindow_ReplaceWith {
            get {
                return ResourceManager.GetString("SearchWindow.ReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search.
        /// </summary>
        public static string SearchWindow_Search {
            get {
                return ResourceManager.GetString("SearchWindow.Search", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search backwards.
        /// </summary>
        public static string SearchWindow_SearchBackwards {
            get {
                return ResourceManager.GetString("SearchWindow.SearchBackwards", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Text to search.
        /// </summary>
        public static string SearchWindow_SearchedText {
            get {
                return ResourceManager.GetString("SearchWindow.SearchedText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search mode.
        /// </summary>
        public static string SearchWindow_SearchMode {
            get {
                return ResourceManager.GetString("SearchWindow.SearchMode", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Extended (\n, \t etc.).
        /// </summary>
        public static string SearchWindow_SearchModeExtended {
            get {
                return ResourceManager.GetString("SearchWindow.SearchModeExtended", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Normal.
        /// </summary>
        public static string SearchWindow_SearchModeNormal {
            get {
                return ResourceManager.GetString("SearchWindow.SearchModeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Regular expressions.
        /// </summary>
        public static string SearchWindow_SearchModeRegex {
            get {
                return ResourceManager.GetString("SearchWindow.SearchModeRegex", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search options.
        /// </summary>
        public static string SearchWindow_SearchOptions {
            get {
                return ResourceManager.GetString("SearchWindow.SearchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search.
        /// </summary>
        public static string SearchWindow_SearchTab {
            get {
                return ResourceManager.GetString("SearchWindow.SearchTab", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Search.
        /// </summary>
        public static string SearchWindow_Title {
            get {
                return ResourceManager.GetString("SearchWindow.Title", resourceCulture);
            }
        }
    }
}
