//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dev.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string BlankDocName {
            get {
                return ResourceManager.GetString("BlankDocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev.Editor.
        /// </summary>
        public static string DefaultDialogTitle {
            get {
                return ResourceManager.GetString("DefaultDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        public static string DefaultFilter {
            get {
                return ResourceManager.GetString("DefaultFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Ribbon_Edit_Copy {
            get {
                return ResourceManager.GetString("Ribbon.Edit.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Ribbon_Edit_Cut {
            get {
                return ResourceManager.GetString("Ribbon.Edit.Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Ribbon_Edit_Paste {
            get {
                return ResourceManager.GetString("Ribbon.Edit.Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Ribbon_Edit_Redo {
            get {
                return ResourceManager.GetString("Ribbon.Edit.Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Ribbon_Edit_Undo {
            get {
                return ResourceManager.GetString("Ribbon.Edit.Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Ribbon_File_New {
            get {
                return ResourceManager.GetString("Ribbon.File.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Ribbon_File_Open {
            get {
                return ResourceManager.GetString("Ribbon.File.Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Ribbon_File_Save {
            get {
                return ResourceManager.GetString("Ribbon.File.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string Ribbon_File_SaveAs {
            get {
                return ResourceManager.GetString("Ribbon.File.SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Ribbon_Group_Edit {
            get {
                return ResourceManager.GetString("Ribbon.Group.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Ribbon_Group_File {
            get {
                return ResourceManager.GetString("Ribbon.Group.File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Ribbon_Group_Search {
            get {
                return ResourceManager.GetString("Ribbon.Group.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Ribbon_Search_Replace {
            get {
                return ResourceManager.GetString("Ribbon.Search.Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Ribbon_Search_Search {
            get {
                return ResourceManager.GetString("Ribbon.Search.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Ribbon_Tab_Home {
            get {
                return ResourceManager.GetString("Ribbon.Tab.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case sensitive.
        /// </summary>
        public static string SearchWindow_CaseSensitive {
            get {
                return ResourceManager.GetString("SearchWindow.CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string SearchWindow_Close {
            get {
                return ResourceManager.GetString("SearchWindow.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find next.
        /// </summary>
        public static string SearchWindow_FindNext {
            get {
                return ResourceManager.GetString("SearchWindow.FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only full words.
        /// </summary>
        public static string SearchWindow_OnlyFullWords {
            get {
                return ResourceManager.GetString("SearchWindow.OnlyFullWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string SearchWindow_Replace {
            get {
                return ResourceManager.GetString("SearchWindow.Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace all.
        /// </summary>
        public static string SearchWindow_ReplaceAll {
            get {
                return ResourceManager.GetString("SearchWindow.ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string SearchWindow_ReplaceTab {
            get {
                return ResourceManager.GetString("SearchWindow.ReplaceTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with.
        /// </summary>
        public static string SearchWindow_ReplaceWith {
            get {
                return ResourceManager.GetString("SearchWindow.ReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchWindow_Search {
            get {
                return ResourceManager.GetString("SearchWindow.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search backwards.
        /// </summary>
        public static string SearchWindow_SearchBackwards {
            get {
                return ResourceManager.GetString("SearchWindow.SearchBackwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to search.
        /// </summary>
        public static string SearchWindow_SearchedText {
            get {
                return ResourceManager.GetString("SearchWindow.SearchedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search mode.
        /// </summary>
        public static string SearchWindow_SearchMode {
            get {
                return ResourceManager.GetString("SearchWindow.SearchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended (\n, \t etc.).
        /// </summary>
        public static string SearchWindow_SearchModeExtended {
            get {
                return ResourceManager.GetString("SearchWindow.SearchModeExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string SearchWindow_SearchModeNormal {
            get {
                return ResourceManager.GetString("SearchWindow.SearchModeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expressions.
        /// </summary>
        public static string SearchWindow_SearchModeRegex {
            get {
                return ResourceManager.GetString("SearchWindow.SearchModeRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search options.
        /// </summary>
        public static string SearchWindow_SearchOptions {
            get {
                return ResourceManager.GetString("SearchWindow.SearchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchWindow_SearchTab {
            get {
                return ResourceManager.GetString("SearchWindow.SearchTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchWindow_Title {
            get {
                return ResourceManager.GetString("SearchWindow.Title", resourceCulture);
            }
        }
    }
}
